### ISSUE TITLE
error building default biped

### ISSUE THREAD

**Issue by mgidney** [nilouco/dpAutoRigSystem#14]
Hi
If I build the default biped I get no symmetry in the arms and legs - and these errors are thrown.

Created Biped Guides.
Warning: Unrecognized node type 'quatToEuler'; preserving node information during this session.  
Error: RuntimeError: file /Users/Shared/UTS_Dev/gitRepositories/utsdab_repos/usr/etc/maya/dab_modules/DABMOD/python/dpAutoRigSystem/Modules/dpLimb.py line 1111: The destination attribute 'L_Leg_Leg_Jxt_ExtactAngle_QtE.inputQuat.inputQuatZ' cannot be found. 

Im using maya 2019 on a mac

**Comment by nilouco** [comment]
Hi mgidney!
Thank you for your feedback.
I think we need to have the quatNodes.mll Maya plugin loaded in order to use the quatToEuler node correctly.
Sorry, I'll load this native Maya plugin before create limb modules.
Hope we have this fix soon :)
Thanks again!
Cheers, Danilo.

**Comment by nilouco** [comment]
Hi mgidney,

update your script with this new commit, please.
And let me know if it is fixed or if you have any problem.
Sorry for this issue and thank you again for your feedback!

Best, Danilo.

**Comment by mgidney** [comment]
Hi Danilo,
That fixed it - thank you.  Ill roll the fix and update out, cheers.

Matt
