### ISSUE TITLE
No module named sstk.libs.libQt

### ISSUE THREAD

**Issue by mickepe** [nilouco/dpAutoRigSystem#5]
Hello,
I've tried running your latest build and am getting this error when trying to run the tool:
-----------------------------------
Error: importing python modules!!!
No module named sstk.libs.libQt
Error: dpAutoRig UI window !!!

Exception: name 'QtGui' is not defined
Cannot load dpAutoRig UI window..., please try save the dpAutoRigSystem folder in MAYA_PATH directory and verify if you did not changed any file. 
dpAutoRigSystem loaded with success.
-------------------------------------
I've put the dpAutoRigSystem both in the 2016 scripts folder and the site-packages folder. The instructions seemed to indicate that it should be in both places? I'm on windows 7 and am using Maya 2016. If there's anything else I can provide, please let me know!

**Comment by sbourgoing** [comment]
Should be fix in the latest pull request ! If you have any problem with the auto-rig, let us know !
