### ISSUE TITLE
Trocar prefixo para "dpAR_3_"

### ISSUE THREAD

**Issue by oseiasmribeiro** [nilouco/dpAutoRigSystem#75]
O prefixo "dpAR_2_" não deveria ter sido trocado para "dpAR_3_" nas versões 3 em diante?

**Comment by nilouco** [comment]
Hi Oseias, what prefix do you mean?

**Comment by oseiasmribeiro** [comment]
I posted an image to illustrate:
![prefix](https://user-images.githubusercontent.com/36827173/148692045-695efa75-335d-4a66-9eca-93d6e86fd65d.jpg)

**Comment by oseiasmribeiro** [comment]
![prefix2](https://user-images.githubusercontent.com/36827173/148694490-89df0965-02b2-40fe-b410-7db79b7b69d2.jpg)

Danilo, I understand better now. When I add the names in the "Edit Module" it removes that prefix. Sorry and thanks.
